name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - foodcart_backend/**
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Backend
        working-directory: foodcart_backend
        run: |
          mvn clean verify

      - name: SonarCloud Scan
        working-directory: foodcart_backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=III-BCA_foodcart-management-system \
            -Dsonar.organization=iii-bca \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN1

      - name: Docker Build
        working-directory: foodcart_backend
        run: |
          docker build -t foodcart-backend .
